"""fix fueling window gel columns

Revision ID: a135208cbf74
Revises: df70a7d0c933
Create Date: 2026-05-14 22:08:45.827502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a135208cbf74'
down_revision: Union[str, Sequence[str], None] = 'df70a7d0c933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fueling_windows', sa.Column('small_gel_id', sa.String(), nullable=True))
    op.add_column('fueling_windows', sa.Column('large_gel_id', sa.String(), nullable=True))
    op.add_column('fueling_windows', sa.Column('n_small_gels', sa.Integer(), nullable=False))
    op.add_column('fueling_windows', sa.Column('n_large_gels', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('fueling_windows_gel_id_fkey'), 'fueling_windows', type_='foreignkey')
    op.create_foreign_key(None, 'fueling_windows', 'gels', ['large_gel_id'], ['id'])
    op.create_foreign_key(None, 'fueling_windows', 'gels', ['small_gel_id'], ['id'])
    op.drop_column('fueling_windows', 'n_gels')
    op.drop_column('fueling_windows', 'gel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fueling_windows', sa.Column('gel_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('fueling_windows', sa.Column('n_gels', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fueling_windows', type_='foreignkey')
    op.drop_constraint(None, 'fueling_windows', type_='foreignkey')
    op.create_foreign_key(op.f('fueling_windows_gel_id_fkey'), 'fueling_windows', 'gels', ['gel_id'], ['id'])
    op.drop_column('fueling_windows', 'n_large_gels')
    op.drop_column('fueling_windows', 'n_small_gels')
    op.drop_column('fueling_windows', 'large_gel_id')
    op.drop_column('fueling_windows', 'small_gel_id')
    # ### end Alembic commands ###
