"""initial schema

Revision ID: df70a7d0c933
Revises: 
Create Date: 2026-05-14 22:03:35.412541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df70a7d0c933'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('athletes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('gels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('carbs_g', sa.Integer(), nullable=False),
    sa.Column('glucose_pct', sa.Float(), nullable=False),
    sa.Column('fructose_pct', sa.Float(), nullable=False),
    sa.Column('ratio_phase', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('athlete_id', sa.String(), nullable=False),
    sa.Column('sport_type', sa.String(), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('target_race_time_hours', sa.Float(), nullable=False),
    sa.Column('start_preference', sa.String(), nullable=False),
    sa.Column('preferred_start_date', sa.Date(), nullable=True),
    sa.Column('long_sessions', sa.JSON(), nullable=False),
    sa.Column('carb_tolerance', sa.String(), nullable=False),
    sa.Column('gi_history', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weeks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('target_carbs_g_per_hour', sa.Float(), nullable=False),
    sa.Column('ratio_phase', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('week_id', sa.String(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('duration_option', sa.String(), nullable=False),
    sa.Column('n_fueling_windows', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['week_id'], ['weeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('consumed_vs_plan', sa.String(), nullable=False),
    sa.Column('consumed_ratio', sa.Float(), nullable=False),
    sa.Column('gi_scale', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fueling_windows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('gel_id', sa.String(), nullable=False),
    sa.Column('window_number', sa.Integer(), nullable=False),
    sa.Column('time_minutes', sa.Integer(), nullable=False),
    sa.Column('carbs_target_g', sa.Float(), nullable=False),
    sa.Column('carbs_actual_g', sa.Float(), nullable=False),
    sa.Column('n_gels', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gel_id'], ['gels.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fueling_windows')
    op.drop_table('feedback')
    op.drop_table('sessions')
    op.drop_table('weeks')
    op.drop_table('plans')
    op.drop_table('gels')
    op.drop_table('athletes')
    # ### end Alembic commands ###
